// Runtime tables the app itself owns — answer permalinks (B3), PII reports
// and saved-search alerts (B6) — live in schema `app` on the PRIMARY
// Postgres, never in `site` (the pipeline's schema, which the app only
// reads). Modeled on ~/Code/prospect/lib/runtimeSchema.ts: idempotent DDL run
// once per process at boot (see instrumentation.ts), safe to run on every
// replica concurrently because every statement is CREATE ... IF NOT EXISTS.
//
// B1 only creates the schema itself and a placeholder migrations table, so
// concurrent `CREATE SCHEMA IF NOT EXISTS` calls from two replicas booting
// at once have somewhere to land without racing each other. The actual
// runtime tables (answers, pii_reports, saved_searches, ...) belong to the
// workstreams that read and write them — add them here, not in a new file,
// so there is exactly one place that owns "what runtime state exists".
import { query } from './db';

export const RUNTIME_DDL = `
CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.runtime_migrations (
  id SERIAL PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  note TEXT
);

-- B3 (Ask): frozen answers, permalinked at /a/<id>. Only a validated,
-- non-empty answer is ever written here — see lib/ask/store.ts.
CREATE TABLE IF NOT EXISTS app.answers (
  id TEXT PRIMARY KEY,
  q TEXT NOT NULL,
  plan JSONB NOT NULL,
  answer JSONB NOT NULL,
  cites JSONB NOT NULL,
  model TEXT NOT NULL,
  usage JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- B3 (Ask): the running daily USD total for the model calls Ask makes, so
-- ASK_DAILY_USD_CAP can be enforced across restarts — see lib/ask/spend.ts
-- for the per-replica caveat (two Dokploy replicas each enforce this cap
-- independently against the same shared total).
CREATE TABLE IF NOT EXISTS app.ask_spend (
  day DATE PRIMARY KEY,
  usd NUMERIC NOT NULL DEFAULT 0,
  calls INTEGER NOT NULL DEFAULT 0
);

-- B17 (Ask follow-ups, issue #23): threads a follow-up turn to the answer it
-- was asked from, so /a/<id> can render the whole chain. ALTER ... ADD
-- COLUMN IF NOT EXISTS keeps this tolerant of an install where app.answers
-- already exists without the column (COMMON-web.md "schema first, code
-- second") — safe to run concurrently on every replica, like the rest of
-- this file. See lib/ask/store.ts's saveAnswer/getAnswerChain.
ALTER TABLE app.answers ADD COLUMN IF NOT EXISTS parent_id TEXT REFERENCES app.answers(id);
CREATE INDEX IF NOT EXISTS answers_parent_id_idx ON app.answers (parent_id);

-- B19 (Accounts, issue #21): Better Auth's own tables, hand-written to match
-- the schema the installed better-auth@1.7.x (magic-link plugin only, no
-- OAuth) actually creates -- verified by reading
-- @better-auth/core/dist/db/get-tables.mjs's buildAuthTables() for this
-- exact package version rather than guessing from docs, since column names
-- have drifted between major versions upstream (e.g. account.providerId).
-- Written here (idempotent CREATE ... IF NOT EXISTS), not generated by the
-- @better-auth/cli migrate command, so a fresh boot on either replica is
-- enough -- no separate migration step for Henry to run. lib/auth/pool.ts
-- points Better Auth's own pg Pool at this schema via search_path=app, so
-- Better Auth's unqualified "user"/"session"/... queries land here.
CREATE TABLE IF NOT EXISTS app."user" (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL UNIQUE,
  "emailVerified" BOOLEAN NOT NULL DEFAULT false,
  image TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app.session (
  id TEXT PRIMARY KEY,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  token TEXT NOT NULL UNIQUE,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "userId" TEXT NOT NULL REFERENCES app."user"(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS session_user_id_idx ON app.session ("userId");

CREATE TABLE IF NOT EXISTS app.account (
  id TEXT PRIMARY KEY,
  "accountId" TEXT NOT NULL,
  "providerId" TEXT NOT NULL,
  "userId" TEXT NOT NULL REFERENCES app."user"(id) ON DELETE CASCADE,
  "accessToken" TEXT,
  "refreshToken" TEXT,
  "idToken" TEXT,
  "accessTokenExpiresAt" TIMESTAMPTZ,
  "refreshTokenExpiresAt" TIMESTAMPTZ,
  scope TEXT,
  password TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS account_user_id_idx ON app.account ("userId");

CREATE TABLE IF NOT EXISTS app.verification (
  id TEXT PRIMARY KEY,
  identifier TEXT NOT NULL,
  value TEXT NOT NULL,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS verification_identifier_idx ON app.verification (identifier);

-- B19: case folder sync (docs/PLAN.md Accounts section). One row per saved
-- page, keyed by (user_id, doc, page) so a merge on sign-in is a plain
-- upsert -- see lib/case/account.ts. "note" and "sort_order" are the only
-- mutable fields once a row exists (besides removal), matching the
-- localStorage CaseItem shape in lib/case/types.ts.
CREATE TABLE IF NOT EXISTS app.case_folders (
  user_id TEXT NOT NULL REFERENCES app."user"(id) ON DELETE CASCADE,
  doc TEXT NOT NULL,
  page INTEGER NOT NULL,
  bates_page TEXT NOT NULL,
  label TEXT NOT NULL DEFAULT '',
  box TEXT,
  agency TEXT,
  volume TEXT,
  note TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  saved_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, doc, page)
);
CREATE INDEX IF NOT EXISTS case_folders_user_sort_idx ON app.case_folders (user_id, sort_order);

-- B19: saved searches (docs/PLAN.md Accounts section). params is the
-- search page's own query string (q, agency, box, contaminant, ...) so
-- re-running it is exactly /search?<params>. last_seen_count and
-- last_checked_at are what web/scripts/digest.ts advances after computing
-- what's new since the last run.
CREATE TABLE IF NOT EXISTS app.saved_searches (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES app."user"(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  params TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_checked_at TIMESTAMPTZ,
  last_seen_count INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS saved_searches_user_idx ON app.saved_searches (user_id);
`;

let ensured: Promise<void> | undefined;

export function ensureRuntimeSchema(): Promise<void> {
  ensured ??= query(RUNTIME_DDL).then(
    () => undefined,
    (err: unknown) => {
      ensured = undefined;
      throw err;
    },
  );
  return ensured;
}
