const $ = id => document.getElementById(id);
const sources = [
 {page:11,bates:'NYC-WTC_000150792',image:'assets/pearl-street.webp',claim:'Cleanup is recorded at five Pearl Street addresses.',explanation:'The five addresses appear together with “Completed” in the cleanup column.',limit:'This is a cleanup record, not a positive asbestos laboratory result.',quote:'“205 PEARL STREET” … “Completed”',url:'https://911records.nyc/doc/NYC-WTC_000150782/p/11',alt:'Original DEP list showing the five Pearl Street addresses and Completed entries',box:['15.5%','18.2%','57.5%','17.5%']},
 {page:1,bates:'NYC-WTC_000150782',image:'assets/list-heading.webp',claim:'The list concerns exterior cleaning by NYC DEP.',explanation:'The heading supplies context for the Pearl Street entries on page 11: this is a record of building exteriors cleaned.',limit:'The heading does not describe indoor conditions or report asbestos sample results.',quote:'“BUILDING EXTERIORS CLEANED BY NYC DEP”',url:'https://911records.nyc/doc/NYC-WTC_000150782',alt:'First page of DEP list headed Building Exteriors Cleaned by NYC DEP',box:['8.5%','15.5%','59%','4%']}
];
let selected=0,highlight=true;
function choose(i){selected=i;const s=sources[i];for(const k of ['claim','explanation','limit','quote','bates'])$(k).textContent=s[k];$('scan').src=$('zoom-image').src=s.image;$('scan').alt=$('zoom-image').alt=s.alt;$('open').href=$('zoom-link').href=s.url;$('unavailable').querySelector('a').href=s.url;$('page-label').textContent=$('zoom-label').textContent=`Original scan · page ${s.page} of 14`;['left','top','width','height'].forEach((k,n)=>$('highlight').style[k]=s.box[n]);document.querySelectorAll('.sources button').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.source)===i)));$('copy').textContent='Copy citation';}
document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{choose(Number(b.dataset.source));$('panel').hidden=false;$('collapse').setAttribute('aria-expanded','true');$('collapse').textContent='Hide preview −';document.querySelector('.evidence').hidden=false;if(b.classList.contains('cite'))document.querySelector('.evidence').scrollIntoView({block:'nearest'});});
$('collapse').onclick=()=>{const hidden=!$('panel').hidden;$('panel').hidden=hidden;$('collapse').setAttribute('aria-expanded',String(!hidden));$('collapse').textContent=hidden?'Show evidence +':'Hide preview −';};
for(const mode of ['desktop','mobile'])$(mode).onclick=()=>{$('conversation').classList.toggle('mobile',mode==='mobile');$('desktop').setAttribute('aria-pressed',String(mode==='desktop'));$('mobile').setAttribute('aria-pressed',String(mode==='mobile'));};
$('state').onchange=()=>{const v=$('state').value;document.querySelector('.evidence').hidden=v==='answer';$('scan-button').hidden=v==='missing';$('unavailable').hidden=v!=='missing';$('enlarge').disabled=v==='missing';$('highlight-toggle').disabled=v==='missing';};
$('highlight-toggle').onclick=()=>{highlight=!highlight;$('highlight').hidden=!highlight;$('highlight-toggle').textContent=highlight?'Highlight on':'Highlight off';$('highlight-toggle').setAttribute('aria-pressed',String(highlight));};
function enlarge(){$('zoom').showModal();}$('enlarge').onclick=$('scan-button').onclick=enlarge;$('close').onclick=()=>$('zoom').close();
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(sources[selected].bates+' · page '+sources[selected].page+'\n'+sources[selected].url);$('copy').textContent='Copied';}catch{$('copy').textContent=sources[selected].bates;}};
