import Link from 'next/link';
import { PageShell } from '@/components/info/PageShell';
import { ReportForm } from '@/components/info/ReportForm';
import { pageMetadata } from '@/lib/info/metadata';
export async function generateMetadata() { return pageMetadata('Personal-information policy','How we handle City redactions, reports of personal information, identity questions and changed records.','/personal-information'); }
export default async function Policy({ searchParams }: { searchParams: Promise<{ bates?: string; received?: string }> }) {
  const {bates,received} = await searchParams;
  return <PageShell prose><div className="eyebrow">Collection policy</div><h1>Protect people. Keep the record checkable.</h1><p className="subtitle">Appearing in a record implies nothing about anyone, including wrongdoing, exposure or illness.</p><section><h2>The City’s records and redactions</h2><p>We serve the City’s records as the City publishes them, including its redactions. We do not run our own redaction pass yet. The City says personal information may have been missed; a visible detail is not a reason to identify or profile someone.</p><p>We do not create private-person entity pages, suggestions, co-mention features or social graphs. Official actions may be indexed only in an official capacity, with the role and supporting record.</p></section><section id="report"><h2>Report a missed redaction</h2><p>Give the Bates page and the location of the information; do not repeat the private details. Reports are stored privately for review by Cleartext Labs. No account or email address is required.</p><p>You can also report directly through the <a href="https://sept11documents.cityofnewyork.us/">City’s official portal</a>.</p>{received && /^[0-9a-f-]{36}$/.test(received) && <p role="status" className="coverage">Report received. Reference: {received}. Keep this reference.</p>}<ReportForm bates={bates && /^NYC-WTC_\d{9}$/.test(bates) ? bates : ''} /></section><section><h2>Response standard</h2><p>Our response standard is to acknowledge reports within 24 hours, restrict the reported region while reviewing within 24 hours of receipt, and review the page and linked copies within 72 hours. If review takes longer, maintain the restriction and update the reporter every 72 hours where a reply channel is available.</p><p>This form acknowledges receipt on screen and does not collect contact details. Review and temporary restrictions require operator action; submitting a report does not automatically redact or hide a page.</p></section><section id="refusal"><h2>Identity questions are refused</h2><p>I can’t help identify a redacted person or reconstruct private identities. You can search building conditions, test results, dates, offices and officials’ actions on records.</p></section><section><h2>When the City changes a page</h2><p>We keep pulling updates from the City. We serve the newest mirrored version of a replaced PDF. Documents the City removes are not served publicly; their references resolve to a removal notice and safe metadata. Older captures are not a way around a redaction.</p><p><Link href="/changes">Capture and change history →</Link></p></section><section><h2>City 9/11 records only</h2><p>This service covers the City’s 9/11 records. Suggestions connect records through subjects, places, substances, offices and dates. No social graph or private-person discovery.</p></section></PageShell>;
}
