/* All data and interactions stay local. No search or reporting service is connected. */
window.previewText=function(name,content,type='text/plain'){
 let d=document.getElementById('export-preview');if(!d){d=document.createElement('dialog');d.id='export-preview';d.className='export-preview';d.innerHTML='<h2></h2><p>Prepared locally. Nothing has been submitted. Copy the text below; downloads may be blocked by the preview.</p><textarea readonly aria-label="Export or report text"></textarea><div class="actions"><button class="button primary" data-copy>Copy</button><button class="button" data-download>Try download</button><button class="button" data-dismiss>Close</button></div><p role="status"></p>';document.body.append(d)}
 d.querySelector('h2').textContent=name;d.querySelector('textarea').value=content;d.querySelector('[role=status]').textContent='';
 d.querySelector('[data-copy]').onclick=async()=>{const t=d.querySelector('textarea');t.focus();t.select();try{await navigator.clipboard.writeText(content);d.querySelector('[role=status]').textContent='Copied.'}catch{let ok=false;try{ok=document.execCommand('copy')}catch{}d.querySelector('[role=status]').textContent=ok?'Copied.':'Text selected. Press ⌘C or Ctrl+C to copy.'}};
 d.querySelector('[data-download]').onclick=()=>{const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);d.querySelector('[role=status]').textContent='Download attempted. You can still copy the text here.'};d.querySelector('[data-dismiss]').onclick=()=>d.close();d.showModal();
};
const pageQuotes={58160:'L-04-01 | Lobby debris | 2% chrysotile; L-04-02 | 2nd floor debris | None detected.',58161:'These results are not airborne-fiber measurements.',60214:'Additional sampling at 110 Liberty Street is requested. Signed and approved: Commissioner, Dept. of Environmental Protection.',62110:'A recheck of asbestos sample identifiers for Liberty Street is requested.',60400:'Asbestos laboratory results are not attached to this sheet.',63810:'Handwritten field notes; no reliable OCR text.'};
const peek=document.createElement('aside');peek.className='source-peek';peek.hidden=true;peek.setAttribute('aria-label','Citation source image');peek.innerHTML='<div class="eyebrow">Claim → source image · fictional page</div><blockquote></blockquote><img alt=""><div class="actions"><a class="button small">Open Bates page →</a><button class="button small">Close</button></div>';document.body.append(peek);let peekTimer;let peekTrigger;
function showSource(a){clearTimeout(peekTimer);peekTrigger=a;const n=Number(new URL(a.href,location.href).searchParams.get('page'))||58160;const q=pageQuotes[n]||'Fictional record excerpt. Inspect the full page and its extraction notes.';peek.querySelector('blockquote').textContent='“'+q+'”';peek.querySelector('img').hidden=!pageQuotes[n];peek.querySelector('img').src='data/crop-'+(pageQuotes[n]?n:58160)+'.svg';peek.querySelector('img').alt='Illustrative page-image crop: '+q;peek.querySelector('a').href=a.href;peek.hidden=false;const r=a.getBoundingClientRect();peek.style.left=Math.max(12,Math.min(r.left,innerWidth-482))+'px';peek.style.top=Math.max(12,Math.min(r.bottom+8,innerHeight-peek.offsetHeight-12))+'px'}
peek.querySelector('button').onclick=()=>{peek.hidden=true;peekTrigger?.focus()};peek.onmouseenter=()=>clearTimeout(peekTimer);peek.onmouseleave=()=>peekTimer=setTimeout(()=>peek.hidden=true,300);
document.addEventListener('keydown',e=>{if(e.key==='Escape')peek.hidden=true});
function bindCitations(){document.querySelectorAll('a.citation:not([data-peek])').forEach(a=>{a.dataset.peek='true';a.addEventListener('mouseenter',()=>showSource(a));a.addEventListener('mouseleave',()=>peekTimer=setTimeout(()=>peek.hidden=true,300));a.addEventListener('focus',()=>showSource(a));a.addEventListener('click',e=>{e.preventDefault();showSource(a);peek.querySelector('a').focus()})})}bindCitations();new MutationObserver(bindCitations).observe(document.querySelector('main'),{childList:true,subtree:true});
// Snapshot rule: no uncited answer paragraph can be displayed.
document.querySelectorAll('.answer-copy p').forEach(p=>{if(!p.querySelector('a.citation'))p.remove()});
const file=location.pathname.split('/').pop();document.querySelectorAll('.masthead .nav a').forEach(a=>{if(a.getAttribute('href')===file)a.setAttribute('aria-current','page')});
// Reusable entity typeahead with explicit role-only official entries.
const options=[['lab','Harbor Analytical Laboratory','0.96',58160],['agency/office','Dept. of Environmental Protection — recipient','0.98',60214],['contractor','Harbor Field Services — inspector of record','0.88',90603],['address','110 Liberty Street — sampling location','0.91',58160],['substance','Asbestos — analyte','0.97',58160],['signed by role','DEP commissioner — signatory on sampling request','0.89',60214],['date range','2001-09 through 2003-12','0.94',58160],['Bates number','NYC-WTC_900058160','1.00',58160]];
const input=document.getElementById('entity-input');
if(input){let selected=[];const box=document.getElementById('entity-options'),tokens=document.getElementById('entity-tokens');function drawOptions(){box.replaceChildren();const q=input.value.toLowerCase();const matches=options.filter(o=>(o[0]+' '+o[1]).toLowerCase().includes(q));matches.forEach(o=>{const b=document.createElement('button');b.type='button';const t=document.createElement('span');t.textContent=o[0]+': '+o[1];const confidence=document.createElement('small');confidence.textContent='Machine-extracted · '+o[2];b.append(t,confidence);b.onclick=()=>{if(!selected.includes(o))selected.push(o);input.value='';box.replaceChildren();drawTokens();input.focus()};box.append(b)});if(!matches.length)box.textContent='No eligible fixture entity. Private individuals are not searchable.'}function drawTokens(){tokens.replaceChildren();selected.forEach(o=>{const b=document.createElement('button');b.textContent=o[0]+': '+o[1]+' ×';b.setAttribute('aria-label','Remove '+o[0]+' '+o[1]);b.onclick=()=>{selected=selected.filter(x=>x!==o);drawTokens()};tokens.append(b);const source=document.createElement('a');source.href='document.html?page='+o[3]+'#page';source.textContent='Check '+o[0]+' · '+o[2];source.className='extraction';tokens.append(source)})}input.oninput=drawOptions;input.onfocus=drawOptions;input.onkeydown=e=>{if(e.key==='ArrowDown'){e.preventDefault();box.querySelector('button')?.focus()}if(e.key==='Escape')box.replaceChildren()};box.onkeydown=e=>{if(e.key==='ArrowDown'){e.preventDefault();(e.target.nextElementSibling||box.firstElementChild)?.focus()}if(e.key==='ArrowUp'){e.preventDefault();(e.target.previousElementSibling||input)?.focus()}};document.getElementById('entity-go').onclick=()=>{const q=document.getElementById('free-text').value;location.href='results.html?q='+encodeURIComponent(q)+'&entities='+encodeURIComponent(selected.map(o=>o[0]+': '+o[1]).join(' · '))};selected=[options[0],options[4]];drawTokens()}
if(file==='results.html'){const search=new URLSearchParams(location.search);const note=document.createElement('div');note.className='entity-results-note coverage';if(search.has('entities')){note.textContent='Selected entity filters: '+search.get('entities')+'. Showing a fixed fixture result set; live filtering is not connected.';document.querySelector('.results-layout').before(note)}else if(search.has('similar')){note.textContent='More like page NYC-WTC_9'+search.get('similar').padStart(8,'0')+(search.has('passage')?' · Passage: “'+search.get('passage')+'”':'')+' · Ranked fixture suggestions by subject similarity.';document.querySelector('.results-layout').before(note)}}
if(file==='entity.html'){const type=new URLSearchParams(location.search).get('type')||'lab';const entries={lab:['Laboratory','Harbor Analytical Laboratory','Analyzing lab / certifying laboratory','0.96',2,[['Analyzed / certified',58160,'Bulk-material sampling table'],['Mentioned as analyzing lab',58161,'Sampling notes']]],agency:['Agency / office','Dept. of Environmental Protection','Issuing office / recipient / cc recipient','0.98',3,[['Issued',58160,'Field sampling record'],['Issued',58161,'Sampling notes'],['Received / cc’d',60214,'Additional sampling request']]],contractor:['Contractor','Harbor Field Services','Inspection contractor / inspector of record','0.88',1,[['Inspected',90603,'Building inspection form']]],substance:['Substance','Asbestos','Analyte / mentioned in sampling request','0.97',3,[['Analyzed',58160,'Bulk-material sampling table'],['Mentioned',58161,'Scope of sampling'],['Mentioned',60214,'Additional sampling request']]]};const d=entries[type]||entries.lab;document.getElementById('entity-kind').textContent=d[0];document.getElementById('entity-name').textContent=d[1];document.getElementById('entity-role').textContent=d[2];document.getElementById('entity-confidence').textContent='confidence '+d[3];document.getElementById('entity-page-count').textContent=d[4];document.getElementById('entity-doc-count').textContent=type==='agency'||type==='substance'?2:1;document.getElementById('activity-count').textContent=d[4]+' pages';const root=document.getElementById('entity-groups');d[5].forEach(([role,n,title])=>{const section=document.createElement('section');section.className='source-item';section.innerHTML='<h3>'+role+'</h3><p>'+title+' · '+d[1]+' ('+role.toLowerCase()+')</p><a class="citation" href="document.html?page='+n+'#page">NYC-WTC_9'+String(n).padStart(8,'0')+' ↗</a><p class="extraction">Machine-extracted · confidence '+d[3]+'</p>';root.append(section)});const headingSource=document.querySelector('.page-title .citation');headingSource.href='document.html?page='+d[5][0][1]+'#page';headingSource.textContent='NYC-WTC_9'+String(d[5][0][1]).padStart(8,'0')+' ↗'}
if(file==='topics.html'){let selected=document.querySelector('[data-topic]');const title=document.getElementById('topic-title'),meta=document.getElementById('topic-meta'),docs=document.getElementById('topic-docs'),level=document.getElementById('topic-level');function select(b){selected=b;title.textContent=b.dataset.title;meta.textContent=b.dataset.pages+' fixture pages · Boxes '+b.dataset.boxes+' · '+b.dataset.span;docs.replaceChildren();level.textContent='Collection → topic';history.replaceState(null,'','#'+b.dataset.topic)}document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>select(b));document.getElementById('topic-zoom').onclick=()=>{level.textContent='Topic → sub-topic → pages';title.textContent=selected.dataset.sub;const n=selected.dataset.topic==='air'?60400:selected.dataset.topic==='sampling'?58160:selected.dataset.topic==='lab'||selected.dataset.topic==='correspondence'?62110:60214;docs.innerHTML='<p>Fixture sub-topic assignment · machine-extracted · confidence 0.84</p><a class="question-link" href="document.html?page='+n+'">Open representative document →</a><a class="citation" href="document.html?page='+n+'#page">NYC-WTC_9'+String(n).padStart(8,'0')+'</a><p>Follow the related-record section for filings in other boxes.</p>'};document.getElementById('topic-reset').onclick=()=>{title.textContent='Whole collection';meta.textContent='24,436 PDFs · 172,537 pages. Select a subject region to zoom in.';level.textContent='Collection';docs.replaceChildren();history.replaceState(null,'','topics.html')};if(location.hash){const b=document.querySelector('[data-topic="'+CSS.escape(location.hash.slice(1))+'"]');if(b)select(b)}}
if(file==='document.html'){const jump=new URLSearchParams(location.search).get('highlight');if(jump){document.getElementById('within').value=jump;document.getElementById('find-hit').click();const cells=document.querySelectorAll('#scan-content td');cells.forEach(c=>{if(c.textContent.toLowerCase().includes(jump.toLowerCase()))c.style.background='#e7edc4'})}document.getElementById('scan-content').id='scan-content';if(location.hash==='#report')document.getElementById('report').click()}
// Home and results keep entity search adjacent to Ask anything.
document.querySelectorAll('form[data-search]').forEach(f=>{const a=document.createElement('a');a.href='entities.html';a.className='question-link';a.textContent='Search by entity · lab, office, contractor, address, substance or signatory role →';f.after(a)});
